#!/usr/bin/env bash
#
#  HERMES — Agent Operations Console
#  Powered by the OpenClaw runtime
#
#  Install:   curl -fsSL https://raw.githubusercontent.com/at0m-b0mb/hermes-console/main/install.sh | bash
#  Or local:  ./install.sh
#
set -euo pipefail

REPO="${HERMES_REPO:-at0m-b0mb/hermes-console}"
BRANCH="${HERMES_BRANCH:-main}"
HOME_DIR="${HERMES_HOME:-$HOME/.hermes}"
APP_DIR="$HOME_DIR/app"
BIN_DIR="${HERMES_BIN:-$HOME/.local/bin}"
MIN_PY_MINOR=9

GOLD=$'\033[38;5;179m'; INDIGO=$'\033[38;5;62m'; GREEN=$'\033[38;5;79m'
RED=$'\033[38;5;167m'; DIM=$'\033[2m'; BOLD=$'\033[1m'; OFF=$'\033[0m'

say()  { printf '  %s\n' "$*"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$OFF" "$*"; }
warn() { printf '  %s!%s %s\n' "$GOLD" "$OFF" "$*"; }
die()  { printf '\n  %s✗ %s%s\n\n' "$RED" "$*" "$OFF" >&2; exit 1; }

banner() {
  printf '%s\n' "$GOLD"
  cat <<'ART'
  ╦ ╦ ╔═╗ ╦═╗ ╔╦╗ ╔═╗ ╔═╗
  ╠═╣ ║╣  ╠╦╝ ║║║ ║╣  ╚═╗
  ╩ ╩ ╚═╝ ╩╚═ ╩ ╩ ╚═╝ ╚═╝
ART
  printf '%s  %sAgent Operations Console · OpenClaw runtime%s\n\n' "$OFF" "$DIM" "$OFF"
}

# ---------------------------------------------------------------- 1. python
find_python() {
  for candidate in python3 python3.13 python3.12 python3.11 python3.10 python3.9 python; do
    if command -v "$candidate" >/dev/null 2>&1; then
      if "$candidate" -c "import sys; sys.exit(0 if sys.version_info >= (3, $MIN_PY_MINOR) else 1)" 2>/dev/null; then
        echo "$candidate"; return 0
      fi
    fi
  done
  return 1
}

# ------------------------------------------------------------- 2. get source
fetch_source() {
  local here; here="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || echo "")"
  if [ -n "$here" ] && [ -d "$here/hermes" ] && [ -f "$here/hermes/__main__.py" ]; then
    say "Installing from this directory."
    rm -rf "$APP_DIR"; mkdir -p "$APP_DIR"
    cp -R "$here/hermes" "$APP_DIR/hermes"
    return
  fi

  command -v curl >/dev/null 2>&1 || die "curl is required to download Hermes."
  local tmp; tmp="$(mktemp -d)"
  say "Downloading Hermes from github.com/$REPO …"
  if ! curl -fsSL "https://codeload.github.com/$REPO/tar.gz/refs/heads/$BRANCH" -o "$tmp/h.tgz"; then
    die "Download failed. Check the repo name ($REPO) and your connection."
  fi
  tar -xzf "$tmp/h.tgz" -C "$tmp"
  local src; src="$(find "$tmp" -maxdepth 2 -type d -name hermes -not -path '*/hermes/hermes' | head -1)"
  [ -n "$src" ] || die "Downloaded archive did not contain the hermes package."
  rm -rf "$APP_DIR"; mkdir -p "$APP_DIR"
  cp -R "$src" "$APP_DIR/hermes"
  rm -rf "$tmp"
}

# -------------------------------------------------------------- 3. launcher
write_launcher() {
  mkdir -p "$BIN_DIR"
  cat > "$BIN_DIR/hermes" <<LAUNCHER
#!/usr/bin/env bash
# Hermes launcher — generated by install.sh
exec "$PY" -c 'import sys; sys.path.insert(0, "$APP_DIR"); from hermes.__main__ import main; sys.exit(main())' "\$@"
LAUNCHER
  chmod +x "$BIN_DIR/hermes"
}

# ---------------------------------------------------------------- 4. ollama
offer_ollama() {
  if command -v ollama >/dev/null 2>&1; then
    if curl -fsS -m 3 http://localhost:11434/api/tags >/dev/null 2>&1; then
      local n; n=$(curl -fsS -m 3 http://localhost:11434/api/tags | tr ',' '\n' | grep -c '"name"' || echo 0)
      if [ "$n" -gt 0 ]; then ok "Ollama is running with $n model(s) — Hermes can work offline and free."
      else warn "Ollama is running but has no models. Pull one:  ollama pull qwen2.5"; fi
    else
      warn "Ollama is installed but not running. Start it:  ollama serve"
    fi
    return
  fi
  warn "Ollama is not installed."
  say "${DIM}Ollama runs models on your own machine — free, offline, private.${OFF}"
  say "${DIM}Install it from https://ollama.com/download, then:  ollama pull qwen2.5${OFF}"
  say "${DIM}You can skip this entirely and use a free API key instead (Groq or Gemini).${OFF}"
}

# ------------------------------------------------------------------- run it
banner

PY="$(find_python)" || die "Python 3.$MIN_PY_MINOR or newer is required. Install it from https://python.org and re-run."
ok "Python $("$PY" -c 'import sys;print("%d.%d.%d"%sys.version_info[:3])') at $(command -v "$PY")"

fetch_source
ok "Installed to $APP_DIR"

mkdir -p "$HOME_DIR"; chmod 700 "$HOME_DIR"
write_launcher
ok "Launcher written to $BIN_DIR/hermes"

# Zero dependencies is the whole point — assert it rather than trust it.
if ! "$PY" -c "import sys; sys.path.insert(0,'$APP_DIR'); import hermes.server, hermes.security, hermes.runtime.engine" 2>/dev/null; then
  die "Hermes failed its import check. Please open an issue at https://github.com/$REPO/issues"
fi
ok "Import check passed — no third-party dependencies needed"

echo
offer_ollama
echo

ON_PATH=0
case ":$PATH:" in *":$BIN_DIR:"*) ON_PATH=1 ;; esac
if [ "$ON_PATH" -eq 0 ]; then
  SHELL_RC="$HOME/.bashrc"
  case "${SHELL:-}" in *zsh) SHELL_RC="$HOME/.zshrc" ;; esac
  warn "$BIN_DIR is not on your PATH."
  say "${DIM}Add it:${OFF}"
  say "  ${BOLD}echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> $SHELL_RC && source $SHELL_RC${OFF}"
  echo
fi

printf '  %s%sHermes is installed.%s\n\n' "$BOLD" "$GREEN" "$OFF"
if [ "$ON_PATH" -eq 1 ]; then
  printf '  Start it:      %s%shermes%s\n' "$BOLD" "$INDIGO" "$OFF"
  printf '  Check setup:   %shermes doctor%s\n' "$DIM" "$OFF"
else
  printf '  Start it:      %s%s%s/hermes%s\n' "$BOLD" "$INDIGO" "$BIN_DIR" "$OFF"
fi
printf '  %sYour browser opens automatically at http://localhost:4317%s\n\n' "$DIM" "$OFF"
